name: Run full matrix Tests before Releases
on:
  - push
  - workflow_call
  - workflow_dispatch
jobs:
  pre-release-matrix-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SGILE_PAT }}
          submodules: recursive
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install sox and use conda to optimize other installs
        run: |
          conda install -y sox $(grep "pycountry\|pyworld" requirements.txt) -c conda-forge
      - name: Install dependencies and package
        run: |
          CUDA_TAG=cpu pip install -r requirements.torch.txt --find-links https://download.pytorch.org/whl/torch_stable.html
          pip install -r requirements.test.txt
          pip install cython
          pip install -e .
      - name: Run tests
        run: |
          cd everyvoice && ./run_tests.py dev
